[package]
name = "spongemock_cli"
description = "A simple CLI tool to Spongemock-ify text."
version = "0.4.0"
license = "MIT"
repository = "https://github.com/Some-Dood/spongemock_cli"
authors = [ "Basti Ortiz <ortizbasti16@gmail.com>" ]
edition = "2018"
resolver = "2"

[[bin]]
name = "spongemock"
path = "src/main.rs"

[dependencies]
clap = { version = "2.34", default-features = false }
rand = { version = "0.8", default-features = false, features = [ "getrandom" ] }
