[package]
name = "spongemock_cli"
description = "A simple CLI tool to Spongemock-ify text."
version = "0.1.0"
license = "MIT"
repository = "https://github.com/Some-Dood/spongemock_cli"
authors = [ "Basti Ortiz <ortizbasti16@gmail.com>" ]
edition = "2018"

[dependencies]
clap = { version = "2.33", default-features = false }
rand = "0.8"
