name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Formatter
      run: cargo fmt --check
    - name: Run Linter
      run: cargo clippy
    - name: Run Tests
      run: cargo test --verbose
