name: Rust

on:
  push:
    branches: [ master ]
    paths: [ 'src/**.rs', 'Cargo.*' ]
  pull_request:
    branches: [ master ]
    paths: [ 'src/**.rs', 'Cargo.*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Formatter
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Linter
      run: cargo clippy
    - name: Tests
      run: cargo test --verbose
